version: '3'

services:

  db:
    container_name: 'export-db-db'
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: 'export-db-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=export-db-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80

  server:
    container_name: 'export-db-server'
    image: nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/srv:cached
    depends_on:
      - php-fpm

  php-fpm:
    container_name: 'export-db-php-fpm'
    build: ./docker/php-fpm
    restart: on-failure
    volumes:
      - ./server:/srv:cached

  composer:
    container_name: 'export-db-composer'
    image: composer
    command: 'composer install -o --ignore-platform-reqs'
    volumes:
      - ./server:/srv:delegated
    working_dir: /srv
